development: &development
#  adapter: postgresql
#  pool: 5
  adapter: mysql2
  encoding: utf8
  database: tp2_dev
  username: root
  #passowrd: 
  host: 127.0.0.1
  port: 3306

test:
  <<: *development
  database: tp2_test

production:
  adapter: postgresql
  encoding: utf8
  database: test_project_two
  username: username
  password: password
  host: host
